name: Check Style

 

on:
  pull_request:
    branches: [ master ]

 

jobs:
  check_style:

 

    runs-on: ubuntu-latest

 

    steps:
    - uses: actions/checkout@v2
    
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.4.0
      with:
        level: 'error'
        fail_on_error: 'true'
